spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/user
#    username: root
#    password: root
    driver-class-name: com.aliyun.polardb.Driver
    url: jdbc:polardb://10.249.161.213:3433/zjww_dev2_0
    username: bdg23_330000_cs
    password: 1
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    # 第一次进行数据库请求就会默认初始化initialSize个connect
    initialSize: 1
    minIdle: 1
    maxActive: 1
    # 配置获取连接等待超时的时间
    maxWait: 20000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 3000
    openMulti: true
    multi:
      - driver-class-name: oracle.jdbc.OracleDriver
        idle-timeout: 20000
        key: 2016
        password: 1
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:oracle:thin:@192.168.2.68:1521:orcl
        username: bdm_normal
      - driver-class-name: oracle.jdbc.OracleDriver
        key: 2019
        password: 1
        url: jdbc:oracle:thin:@192.168.2.68:1521:orcl
        username: bdm_normal
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    filters.stat.log-show-sql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL

    # 启用时将激活atomikos数据源配置
    jta: false
