# 证书配置, 用来生成证书的基本配置信息
license:
  expiryTime: "2032-07-07 19:07:59"
  issuedTime: "2022-07-07 19:07:00"
  keyPass: 12345678A
  privateAlias: SYSHLANG
  licensePath: "/tmp/license.lic"
  privateKeysStorePath: "/tmp/privateKeys.keystore"
  storePass: 12345678A
  subject: "pushi-kn-graph"
  customLicenseParamExt:
#   服务器配置信息
    mainBoardSerial: 41983BBB
#  mac地址
    macAddress:
      - "02-42-41-BD-CE-53"
      - "02-42-BB-4E-81-D5"
      - "02-42-B6-0B-F8-09"
      - "02-42-57-3E-93-B3"
      - "02-42-D6-C4-0C-2C"
      - "02-42-51-73-18-9E"
      - "02-42-99-EE-59-7D"
      - "8C-16-45-32-C5-FF"
#   cpu序列号
    cpuSerial: "EA 06 08 00 FF FB EB BF"
#   地址信息
    ipAddress:
      - "172.23.0.1"
      - "172.18.0.1"
      - "172.22.0.1"
      - "172.21.0.1"
      - "172.19.0.1"
      - "172.17.0.1"
      - "172.20.0.1"
      - "10.10.15.159"
