services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    network_mode: host
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
