version: "2"
services:
  # rabbitmq启动, guest/guest
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
      #    restart: always