version: "2"
services:
  # zipkin 链路追踪
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
#    environment:
#      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
#      - MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
