version: "3"
services:
  mysql:
    image: mysql:5.7.15
    ports:
      - "3306:3306"
      #    restart: always
    volumes:
      - "${HOME}/docker/mysql/data:/var/lib/mysql"
      - "${HOME}/docker/mysql/config/mysql.conf.d:/etc/mysql/mysql.conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: [                        #使用 command 可以覆盖容器启动后默认执行的命令
      '--character-set-server=utf8mb4',            #设置数据库表的数据集
      '--collation-server=utf8mb4_unicode_ci',    #设置数据库表的数据集
      '--default-time-zone=+8:00'                    #设置mysql数据库的 时区问题！！！！ 而不是设置容器的时区问题！！！！
    ]