spring:
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.100.10:1521:pdb19
      username: mid_ox
      password: 1
    mysql:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
    polardb:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
    postgresql:
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      username: postgres
      password: 1
