spring:
#  redisson:
    # 配置单点模式
#    config: classpath:redisson.yml
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
